### PR TITLE
package.json, README -> README.md

### PR DESCRIPTION
**Pull request by StoneCypher**
I added a `package.json` so that `jscheck` could be published on `npm`.  There's a copy from 2014 unmaintained up there right now, which isn't desirable.

I also renamed `README` to `README.md` so that other tools would pick it up.

I will happily give you ownership of the `npm` registration of your tool once you tell me a relevant account name.

### CODE REVIEW

**Comment by StoneCypher** [comment]
Published as `1.0.1` on [npm](https://www.npmjs.com/package/jscheck.js)

**Comment by StoneCypher** [comment]
Also, I was wondering whether you had a best practice document somewhere for user libraries of generators.  I looked, and was unable to locate one

**Comment by douglascrockford** [comment]
If you put it on NPM, you are responsible for it forever. If you neglect it, you will burn in Hell like the bastard who put up the 2014 copy.

**Comment by StoneCypher** [comment]
that's why i was trying to give it over to you `:(`

i'm sorry, buddy.  i was trying to be helpful

**Comment by StoneCypher** [comment]
i was actually going to try to donate some travis stuff so that the maintenance would be automatic, but, maybe that isn't wanted

**Pull request closed without merging**
